# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: financial_agent.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'financial_agent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66inancial_agent.proto\x12\x0f\x66inancial_agent\"K\n\x0b\x43hatRequest\x12\x17\n\x0f\x63onversation_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nmodel_name\x18\x03 \x01(\t\":\n\rToolCallStart\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x16\n\x0e\x61rguments_json\x18\x02 \x01(\t\"P\n\x0bToolCallEnd\x12\x11\n\ttool_name\x18\x01 \x01(\t\x12\x13\n\x0boutput_json\x18\x02 \x01(\t\x12\x19\n\x11\x65xecution_time_ms\x18\x03 \x01(\x03\"1\n\tTextChunk\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x16\n\x0eis_final_chunk\x18\x02 \x01(\x08\"P\n\x15HRPOptimizationResult\x12\x0f\n\x07symbols\x18\x01 \x03(\t\x12\x0f\n\x07weights\x18\x02 \x03(\x02\x12\x15\n\rsummary_notes\x18\x03 \x01(\t\"\xc5\x02\n\x0bStreamEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x11\n\ttimestamp\x18\x02 \x01(\t\x12\x30\n\ntext_chunk\x18\x03 \x01(\x0b\x32\x1a.financial_agent.TextChunkH\x00\x12\x34\n\ntool_start\x18\x04 \x01(\x0b\x32\x1e.financial_agent.ToolCallStartH\x00\x12\x30\n\x08tool_end\x18\x05 \x01(\x0b\x32\x1c.financial_agent.ToolCallEndH\x00\x12<\n\nhrp_result\x18\x06 \x01(\x0b\x32&.financial_agent.HRPOptimizationResultH\x00\x12\x17\n\rerror_message\x18\x07 \x01(\tH\x00\x12\x15\n\x0bis_finished\x18\x08 \x01(\x08H\x00\x42\t\n\x07payloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'financial_agent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHATREQUEST']._serialized_start=42
  _globals['_CHATREQUEST']._serialized_end=117
  _globals['_TOOLCALLSTART']._serialized_start=119
  _globals['_TOOLCALLSTART']._serialized_end=177
  _globals['_TOOLCALLEND']._serialized_start=179
  _globals['_TOOLCALLEND']._serialized_end=259
  _globals['_TEXTCHUNK']._serialized_start=261
  _globals['_TEXTCHUNK']._serialized_end=310
  _globals['_HRPOPTIMIZATIONRESULT']._serialized_start=312
  _globals['_HRPOPTIMIZATIONRESULT']._serialized_end=392
  _globals['_STREAMEVENT']._serialized_start=395
  _globals['_STREAMEVENT']._serialized_end=720
# @@protoc_insertion_point(module_scope)
